name: Rust Tests

on:
  workflow_call:
    inputs:
      safe-checkout:
        required: true
        description: "The SHA key for the commit we want to run over"
        type: string

permissions:
  contents: read

jobs:
  # This job should be run on presubmit, if any continuous-only tests are added we will need to input test-type above
  linux:
      name: Linux Bazel ${{ matrix.bazel-version }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout pending changes
          uses: protocolbuffers/protobuf-ci/checkout@v3
          with:
            ref: ${{ inputs.safe-checkout }}
        - name: Run tests
          uses: protocolbuffers/protobuf-ci/bazel-docker@v3
          with:
            image: "us-docker.pkg.dev/protobuf-build/containers/common/linux/bazel:7.1.2-cf84e92285ca133b9c8104ad7b14d70e953cbb8e"
            credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
            bazel-cache: rust_linux
            bazel: >-
              test --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --incompatible_merge_fixed_and_default_shell_env
              //rust:protobuf_upb_test //rust:protobuf_cpp_test
              //rust/test/rust_proto_library_unit_test:rust_upb_aspect_test
              //src/google/protobuf/compiler/rust/...
